from datetime import datetime
from bson import ObjectId

DEFAULT_TOOLS = [
    {
        "_id": ObjectId("686fd155b567810c3a766ba4"),
        "name": "Google Search Tool",
        "module_path": "agno.tools.googlesearch",
        "class_name": "GoogleSearchTools",
        "description": "Tool to search Google",
        "toolkit": "search",
        "package": "agno.tools",
        "tool_class": "GoogleSearchTools",
        "inputs": [],
        "tags": [],
        "created_at": datetime(2024, 1, 1, 0, 0, 0),
        "image_url": "https://images.icon-icons.com/2699/PNG/512/google_logo_icon_169090.png",
    },
    {
        "_id": ObjectId("6870fa73a3eb27402f979460"),
        "name": "Exa Tools",
        "class_name": "ExaTools",
        "created_at": datetime(2024, 1, 1, 0, 0, 0),
        "description": "Toolset for Exa web search, content retrieval, similarity search, and AI answers.",
        "inputs": [],
        "module_path": "agno.tools.exa",
        "tool_param": "EXA_API_KEY",
        "package": "agno.tools",
        "tags": ["web", "search", "AI", "content"],
        "tool_class": "ExaTools",
        "toolkit": "search",
        "image_url": "https://exa.ai/images/homepage-v2/exa.png",
    },
    {
        "_id": ObjectId("6870fa73a3eb27402f979461"),
        "name": "Email Tool",
        "class_name": "EmailTools",
        "created_at": datetime(2024, 1, 1, 0, 0, 0),
        "description": "Tool to send emails to users with subject and body.",
        "inputs": [],
        "module_path": "agno.tools.email",
        "package": "agno.tools",
        "tags": ["email", "gmail", "notification"],
        "tool_class": "EmailTools",
        "toolkit": "communication",
        "image_url": "https://images.icon-icons.com/2631/PNG/512/gmail_new_logo_icon_159149.png",
    },
    {
        "_id": ObjectId("6870fa73a3eb27402f979462"),
        "name": "WhatsApp Tool",
        "class_name": "WhatsAppTools",
        "created_at": datetime(2024, 1, 1, 0, 0, 0),
        "description": "Tool for sending messages via WhatsApp Business API.",
        "inputs": [],
        "module_path": "agno.tools.whatsapp",
        "package": "agno.tools",
        "tags": ["whatsapp", "messaging", "meta"],
        "tool_class": "WhatsAppTools",
        "toolkit": "communication",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/WhatsApp.svg/1022px-WhatsApp.svg.png",
    },
    {
        "_id": ObjectId("6870fa73a3eb27402f979463"),
        "name": "AgentQL Tool",
        "class_name": "AgentQLTools",
        "created_at": datetime(2024, 1, 1, 0, 0, 0),
        "description": "Tool to browse and scrape websites using AgentQL API.",
        "inputs": [],
        "module_path": "agno.tools.agentql",
        "package": "agno.tools",
        "tags": ["scraping", "browser", "agentql"],
        "tool_class": "AgentQLTools",
        "toolkit": "scraping",
        "image_url": "https://pipedream.com/s.v0/app_Bxh3rA/logo/orig",
    },
    {
        "_id": ObjectId("68b04b912ba59330557e74a7"),
        "name": "Firecrawl",
        "toolkit": "scrapping",
        "package": "agno.tools",
        "tool_class": "FirecrawlTools",
        "description": "FirecrawlTools enable an Agent to perform web crawling and scraping tasks.",
        "module_path": "agno.tools.firecrawl",
        "class_name": "FirecrawlTools",
        "inputs": [],
        "tags": [],
        "visible": True,
        "configurable": False,
        "default_config": {},
        "image_url": "https://cdn.prod.website-files.com/6418bbd648ad4081cf60eb29/6812feab95f460f390d92f03_R5pNLpLkH070Q5E3qgz0cUuztzOYebnfl_VYv8LrFJc.png",
        "created_at": datetime(2025, 8, 28, 12, 29, 5, 116000),
    },
]
